// <auto-generated/>
// slicec-cs version: '0.6.0-preview.1'
// Generated from file: 'Test.slice'

#nullable enable

#pragma warning disable CS1591 // Missing XML Comment
#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0619 // Type or member is obsolete

using ZeroC.Slice.Codec;

namespace Test;

/// <summary>My struct can link to: <paramref name="ccc" />!</summary>
/// <remarks>The Slice compiler generated this record struct from the Slice struct <c>Test::MyStruct</c>.</remarks>
public partial record struct MyStruct
{
    public int A { get; set; }

    /// <summary>Constructs a new instance of <see cref="MyStruct" />.</summary>
    public MyStruct(int a)
    {
        this.A = a;
    }

    /// <summary>Constructs a new instance of <see cref="MyStruct" /> and decodes its fields from a Slice decoder.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    public MyStruct(ref SliceDecoder decoder)
    {
        this.A = decoder.DecodeInt32();
        decoder.SkipTagged();
    }

    /// <summary>Encodes the fields of this struct with a Slice encoder.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    public readonly void Encode(ref SliceEncoder encoder)
    {
        encoder.EncodeInt32(this.A);
        encoder.EncodeVarInt32(SliceDefinitions.TagEndMarker);
    }
}
