// <auto-generated/>
// slicec-cs version: '0.6.0-preview.1'
// Generated from file: 'Test.slice'

#nullable enable

#pragma warning disable CS1591 // Missing XML Comment
#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0619 // Type or member is obsolete

using IceRpc.Slice;
using IceRpc.Slice.Operations;
using ZeroC.Slice.Codec;

namespace Test;

/// <remarks>The Slice compiler generated this client-side interface from Slice interface <c>Test::MyInterface</c>.
/// It's implemented by <see cref="MyInterfaceProxy" />.</remarks>
public partial interface IMyInterface
{
    /// <summary>Line1 links to a <paramref name="aaa" />
    ///  Line2 links to a <paramref name="bbb" />
    ///  Line3 links to a <paramref name="ccc" /></summary>
    /// <param name="aaa">This is for the 1st parameter!</param>
    /// <param name="bbb">This is for the 2nd parameter!</param>
    /// <param name="features">The invocation features.</param>
    /// <param name="cancellationToken">A cancellation token that receives the cancellation requests.</param>
    /// <returns>A tuple containing:
    /// <list type="bullet">
    /// <item><description>This is for the 1st return type!</description></item>
    /// <item><description>This is for the 2nd return type!</description></item>
    /// </list></returns>
    global::System.Threading.Tasks.Task<(bool Bbb, uint Ccc)> Op1Async(
        int aaa,
        string bbb,
        IceRpc.Features.IFeatureCollection? features = null,
        global::System.Threading.CancellationToken cancellationToken = default);
}

/// <summary>Implements <see cref="IMyInterface" /> by making invocations on a remote IceRPC service.
/// This remote service must implement Slice interface Test::MyInterface.</summary>
/// <remarks>The Slice compiler generated this record struct from the Slice interface <c>Test::MyInterface</c>.</remarks>
public readonly partial record struct MyInterfaceProxy : IMyInterface, ISliceProxy
{
    /// <summary>Provides static methods that encode operation arguments into request payloads.</summary>
    /// <remarks>The Slice compiler generated this static class from the Slice interface <c>Test::MyInterface</c>.</remarks>
    public static class Request
    {
        /// <summary>Encodes the arguments of operation <c>op1</c> into a request payload.</summary>
        /// <param name="aaa">This is for the 1st parameter!</param>
        /// <param name="bbb">This is for the 2nd parameter!</param>
        /// <param name="encodeOptions">The Slice encode options.</param>
        /// <returns>The Slice-encoded payload.</returns>
        public static global::System.IO.Pipelines.PipeReader EncodeOp1(
            int aaa,
            string bbb,
            SliceEncodeOptions? encodeOptions = null)
        {
            var pipe_ = new global::System.IO.Pipelines.Pipe(
                encodeOptions?.PipeOptions ?? SliceEncodeOptions.Default.PipeOptions);
            var encoder_ = new SliceEncoder(pipe_.Writer);

            Span<byte> sizePlaceholder_ = encoder_.GetPlaceholderSpan(4);
            int startPos_ = encoder_.EncodedByteCount;

            encoder_.EncodeInt32(aaa);
            encoder_.EncodeString(bbb);
            encoder_.EncodeVarInt32(SliceDefinitions.TagEndMarker);

            SliceEncoder.EncodeVarUInt62((ulong)(encoder_.EncodedByteCount - startPos_), sizePlaceholder_);

            pipe_.Writer.Complete();
            return pipe_.Reader;
        }
    }

    /// <summary>Provides a <see cref="ResponseDecodeFunc{T}" /> for each operation defined in Slice interface Test::MyInterface.</summary>
    /// <remarks>The Slice compiler generated this static class from the Slice interface <c>Test::MyInterface</c>.</remarks>
    public static class Response
    {
        /// <summary>Decodes an incoming response for operation <c>op1</c>.</summary>
        public static global::System.Threading.Tasks.ValueTask<(bool Bbb, uint Ccc)> DecodeOp1Async(
            IceRpc.IncomingResponse response,
            IceRpc.OutgoingRequest request,
            ISliceProxy sender,
            global::System.Threading.CancellationToken cancellationToken) =>
            response.DecodeReturnValueAsync(
                request,
                sender,
                (ref SliceDecoder decoder) =>
                {
                    var sliceP_bbb = decoder.DecodeBool();
                    var sliceP_ccc = decoder.DecodeVarUInt32();
                    return (sliceP_bbb, sliceP_ccc);
                },
                cancellationToken);
    }

    /// <summary>Represents the default path for IceRPC services that implement Slice interface
    /// <c>Test::MyInterface</c>.</summary>
    public const string DefaultServicePath = "/Test.MyInterface";

    /// <inheritdoc/>
    public SliceEncodeOptions? EncodeOptions { get; init; }

    /// <inheritdoc/>
    public required IceRpc.IInvoker Invoker { get; init; }

    /// <inheritdoc/>
    public IceRpc.ServiceAddress ServiceAddress { get; init; } = _defaultServiceAddress;

    private static IceRpc.ServiceAddress _defaultServiceAddress =
        new(IceRpc.Protocol.IceRpc) { Path = DefaultServicePath };

    /// <summary>Creates a relative proxy from a path.</summary>
    /// <param name="path">The path.</param>
    /// <returns>The new relative proxy.</returns>
    public static MyInterfaceProxy FromPath(string path) =>
        new(IceRpc.InvalidInvoker.Instance, new IceRpc.ServiceAddress { Path = path });

    /// <summary>Constructs a proxy from an invoker, a service address and encode options.</summary>
    /// <param name="invoker">The invocation pipeline of the proxy.</param>
    /// <param name="serviceAddress">The service address. <see langword="null" /> is equivalent to an icerpc service address
    /// with path <see cref="DefaultServicePath" />.</param>
    /// <param name="encodeOptions">The encode options, used to customize the encoding of request payloads.</param>
    [System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public MyInterfaceProxy(
        IceRpc.IInvoker invoker,
        IceRpc.ServiceAddress? serviceAddress = null,
        SliceEncodeOptions? encodeOptions = null)
    {
        Invoker = invoker;
        ServiceAddress = serviceAddress ?? _defaultServiceAddress;
        EncodeOptions = encodeOptions;
    }

    /// <summary>Constructs a proxy from an invoker, a service address URI and encode options.</summary>
    /// <param name="invoker">The invocation pipeline of the proxy.</param>
    /// <param name="serviceAddressUri">A URI that represents a service address.</param>
    /// <param name="encodeOptions">The encode options, used to customize the encoding of request payloads.</param>
    [System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
    public MyInterfaceProxy(IceRpc.IInvoker invoker, System.Uri serviceAddressUri, SliceEncodeOptions? encodeOptions = null)
        : this(invoker, new IceRpc.ServiceAddress(serviceAddressUri), encodeOptions)
    {
    }

    /// <summary>Constructs a proxy with an icerpc service address with path <see cref="DefaultServicePath" />.</summary>
    public MyInterfaceProxy()
    {
    }

    /// <inheritdoc/>
    public global::System.Threading.Tasks.Task<(bool Bbb, uint Ccc)> Op1Async(
        int aaa,
        string bbb,
        IceRpc.Features.IFeatureCollection? features = null,
        global::System.Threading.CancellationToken cancellationToken = default) =>
        this.InvokeOperationAsync(
            "op1",
            payload: Request.EncodeOp1(aaa, bbb, encodeOptions: EncodeOptions),
            payloadContinuation: null,
            Response.DecodeOp1Async,
            features,
            cancellationToken: cancellationToken);
}

/// <summary>Provides an extension method for <see cref="SliceEncoder" /> to encode a <see cref="MyInterfaceProxy" />.</summary>
public static class MyInterfaceProxySliceEncoderExtensions
{
    /// <summary>Encodes a <see cref="MyInterfaceProxy" /> as an <see cref="IceRpc.ServiceAddress" />.</summary>
    /// <param name="encoder">The Slice encoder.</param>
    /// <param name="proxy">The proxy to encode as a service address.</param>
    public static void EncodeMyInterfaceProxy(this ref SliceEncoder encoder, MyInterfaceProxy proxy) =>
        encoder.EncodeServiceAddress(proxy.ServiceAddress);
}

/// <summary>Provides an extension method for <see cref="SliceDecoder" /> to decode a <see cref="MyInterfaceProxy" />.</summary>
public static class MyInterfaceProxySliceDecoderExtensions
{
    /// <summary>Decodes an <see cref="IceRpc.ServiceAddress" /> into a <see cref="MyInterfaceProxy" />.</summary>
    /// <param name="decoder">The Slice decoder.</param>
    /// <returns>The proxy created from the decoded service address.</returns>
    public static MyInterfaceProxy DecodeMyInterfaceProxy(this ref SliceDecoder decoder) =>
        decoder.DecodeProxy<MyInterfaceProxy>();
}

/// <remarks>The Slice compiler generated this server-side interface from Slice interface <c>Test::MyInterface</c>.
/// Your service implementation must implement this interface.</remarks>
[IceRpc.DefaultServicePath("/Test.MyInterface")]
public partial interface IMyInterfaceService
{
    /// <summary>Provides static methods that decode request payloads.</summary>
    /// <remarks>The Slice compiler generated this static class from the Slice interface <c>Test::MyInterface</c>.</remarks>
    public static class Request
    {
        /// <summary>Decodes the request payload of operation <c>op1</c>.</summary>
        /// <param name="request">The incoming request.</param>
        /// <param name="cancellationToken">A cancellation token that receives the cancellation requests.</param>
        public static global::System.Threading.Tasks.ValueTask<(int Aaa, string Bbb)> DecodeOp1Async(
            IceRpc.IncomingRequest request,
            global::System.Threading.CancellationToken cancellationToken) =>
            request.DecodeArgsAsync(
                (ref SliceDecoder decoder) =>
                {
                    var sliceP_aaa = decoder.DecodeInt32();
                    var sliceP_bbb = decoder.DecodeString();
                    return (sliceP_aaa, sliceP_bbb);
                },
                cancellationToken);
    }

    /// <summary>Provides static methods that encode return values into response payloads.</summary>
    /// <remarks>The Slice compiler generated this static class from the Slice interface <c>Test::MyInterface</c>.</remarks>
    public static class Response
    {
        /// <summary>Encodes the return value of operation <c>op1</c> into a response payload.</summary>
        /// <param name="bbb">This is for the 2nd parameter!</param>
        /// <param name="encodeOptions">The Slice encode options.</param>
        /// <returns>A new response payload.</returns>
        public static global::System.IO.Pipelines.PipeReader EncodeOp1(
            bool bbb,
            uint ccc,
            SliceEncodeOptions? encodeOptions = null)
        {
            var pipe_ = new global::System.IO.Pipelines.Pipe(
                encodeOptions?.PipeOptions ?? SliceEncodeOptions.Default.PipeOptions);
            var encoder_ = new SliceEncoder(pipe_.Writer);

            Span<byte> sizePlaceholder_ = encoder_.GetPlaceholderSpan(4);
            int startPos_ = encoder_.EncodedByteCount;

            encoder_.EncodeBool(bbb);
            encoder_.EncodeVarUInt32(ccc);
            encoder_.EncodeVarInt32(SliceDefinitions.TagEndMarker);

            SliceEncoder.EncodeVarUInt62((ulong)(encoder_.EncodedByteCount - startPos_), sizePlaceholder_);

            pipe_.Writer.Complete();
            return pipe_.Reader;
        }
    }

    /// <summary>Line1 links to a <paramref name="aaa" />
    ///  Line2 links to a <paramref name="bbb" />
    ///  Line3 links to a <paramref name="ccc" /></summary>
    /// <param name="aaa">This is for the 1st parameter!</param>
    /// <param name="bbb">This is for the 2nd parameter!</param>
    /// <param name="features">The dispatch features.</param>
    /// <param name="cancellationToken">A cancellation token that receives the cancellation requests.</param>
    /// <returns>A tuple containing:
    /// <list type="bullet">
    /// <item><description>This is for the 1st return type!</description></item>
    /// <item><description>This is for the 2nd return type!</description></item>
    /// </list></returns>
    [SliceOperation("op1")]
    public global::System.Threading.Tasks.ValueTask<(bool Bbb, uint Ccc)> Op1Async(
        int aaa,
        string bbb,
        IceRpc.Features.IFeatureCollection features,
        global::System.Threading.CancellationToken cancellationToken);
}
